language: node_js
node_js:
  - 7

branches:
  only:
  - master

before_script:
  - git clone -b gh-pages https://github.com/ffc-nectec/api-doc.git /tmp/api-doc
  - npm install -g aglio

script:
  - aglio -i blueprint.apib -o /tmp/api-doc/index.html
  - cd /tmp/api-doc
  - du -sh *
  - git add index.html
  - git commit -m "Build html"
  - git remote add origin-gh-pages https://${GH_TOKEN}@github.com/ffc-nectec/api-doc.git > /dev/null 2>&1
  - git push --set-upstream origin-gh-pages gh-pages
