language: node_js
node_js:
  - 8

branches:
  only:
  - master

before_script:
  - du -sh /tmp/*
  - git clone -b gh-pages https://github.com/ffc-nectec/api-doc.git /tmp/api-doc
  - ls -al /tmp/api-doc/*
  - npm install -g snowboard

script:
  - ls -al *
  - rsync -av --delete ./data /tmp/api-doc/
  - snowboard apib -o API.apib blueprint.apib
  - tail -n 500 API.apib
  - snowboard lint API.apib
  - snowboard html -o index.html API.apib
  - mv index.html /tmp/index.html
  - cd /tmp/api-doc
  - git checkout gh-pages
  - mv ../index.html .
  - git add data
  - git add index.html
  - git commit -m "Build html"
  - git remote add origin-gh-pages https://${GH_TOKEN}@github.com/ffc-nectec/api-doc.git > /dev/null 2>&1
  - git push --set-upstream origin-gh-pages gh-pages
