@startuml
actor "Super User" as User
User -> "Organization service": Create organization Request POST /org
note left: Organization Body\n id: HEX character length 32.\n users: Need one person is 'ADMIN' in roles.

"Organization service" --> User: Create confirm Response
note right: Organization Body\n id: HEX character length 24.

@enduml
