@startuml
actor User

User -> "Authorize service": Authentication Request
note left: Login body\n{\n  "username":"thanachai",\n  "password":"a1e6-4f63e8295160"\n}

"Authorize service" -> "Authorize service": Check username and password\nCheck activate=true

"Authorize service" --> User: Authentication Response
note right: Token\n{\n  "expireDate":"xxx",\n  ...,\n  "token":"sdfsdfue"\n}

@enduml
